### ISSUE TITLE
登录过期

### ISSUE THREAD

**Issue by tongdeyong** [tongsanghua/tt-admin-vue#1]
1. 登录过期时，弹框连续提示2次才能跳转到页面登录页面
2. 弹框需要点击确认后，才跳转，不美丽，应该时给个延时信息，直接跳转到登录页面即可

**Comment by tongsanghua** [comment]
https://github.com/tongsanghua/tt-admin-vue/commit/257b23475f88fe7a3e327dfeef3aeada26b13345
关于第2点，不做自动跳转的原因是，怕有表单信息未提交，用户可以选择先不跳转，保留表单信息

**Comment by tongdeyong** [comment]
但是，从目前真实的操作来看，并不能达到先不跳转，保留表单的功能
