### ISSUE TITLE
权限选择菜单

### ISSUE THREAD

**Issue by tongdeyong** [tongsanghua/tt-admin-vue#2]
1. 在选择权限菜单时，选择父节点，子节点不能全部选择
2. 子节点一个都没选择时，父节点应该直接被取消选择

**Comment by tongsanghua** [comment]
https://github.com/tongsanghua/tt-admin-vue/commit/3ba7ca987e629d89f9fcc344f81fd6eb8da5315f

**Comment by tongsanghua** [comment]
https://github.com/tongsanghua/tt-admin-vue/commit/9131a70549a8c85da32e627697478aeb45cd233a
